# Generated by Django 3.1.4 on 2020-12-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_inv2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_inv3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField()),
                ('technology', models.CharField(max_length=200)),
                ('github', models.URLField(blank=True)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='project_inv2',
            old_name='image2',
            new_name='image',
        ),
    ]
